name: Prerelease

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Prerelease tag'
        required: true
        type: choice
        options:
          - alpha
          - beta
          - rc

jobs:
  prerelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build packages
        run: pnpm build
      
      - name: Run tests
        run: pnpm test
      
      - name: Enter prerelease mode
        run: pnpm changeset pre enter ${{ github.event.inputs.tag }}
      
      - name: Version packages
        run: pnpm changeset:version
      
      - name: Commit prerelease changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: enter ${{ github.event.inputs.tag }} prerelease mode" || exit 0
      
      - name: Publish prerelease
        run: pnpm changeset:publish --tag ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      
      - name: Push changes
        run: git push --follow-tags